### ISSUE TITLE
The method '$_clearField' isn't defined for the type X.

### ISSUE THREAD

**Issue by Broderick-Westrope** [connectrpc/connect-dart#16]
**Describe the bug**

I followed the quickstart guide for setting up a dart client. The only change I made was to use [the schema](https://buf.build/bufbuild/eliza/file/main:buf/connect/demo/eliza/v1/eliza.proto) from the BSR rather than local proto files. Because of this, I used the command `buf generate buf.build/bufbuild/eliza`. The generation completed without errors (though one warning about the schema being deprecated). The generated files appeared complete but had an error (in VSCode) within `eliza.pb.dart` stating:
```
The method '$_clearField' isn't defined for the type 'SayRequest'.
Try correcting the name to the name of an existing method, or defining a method named '$_clearField'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)
```

This error appeared in six locations within the file, once for each request/response type.

**Environment (please complete the following information):**

```
flutter --version
Flutter 3.29.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ea121f8859 (4 days ago) • 2025-04-11 19:10:07 +0000
Engine • revision cf56914b32
Tools • Dart 3.7.2 • DevTools 2.42.3
```

- connectrpc version: `0.3.0`
- Platform/Device and version: Developing on MacOS 15.4, no other device used.

```yaml
name: test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  connectrpc: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
```

```yaml
version: v2
deps:
  - buf.build/bufbuild/eliza
```

```yaml
version: v2
plugins:
  - remote: buf.build/connectrpc/dart
    out: lib/gen
  - remote: buf.build/protocolbuffers/dart
    out: lib/gen
    include_wkt: true
    include_imports: true
```

It's worth noting that when I tried the same thing with my own (private) proto schema I got the same errors well as another similar error:
```
The method '$_setField' isn't defined for the type '<my-type>Response'.
Try correcting the name to the name of an existing method, or defining a method named '$_setField'.dart[undefined_method](https://dart.dev/diagnostics/undefined_method)
```
